title: climtropy.de
author: ©Bodo Ahrens, 2023
email: "Bodo.Ahrens@iau.uni-frankfurt.de"
description: > # this means to ignore newlines until "show_excerpts:"
  Inofficial Site of the WG Mesoscale Meteorology and Climate @ Goethe Univ. Frankfurt am Main

show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

#ba  # generate social links in footer
#ba  social_links:
#ba    - { platform: devto,          user_url: "https://dev.to/jekyll" }
#ba    - { platform: dribbble,       user_url: "https://dribbble.com/jekyll" }
#ba    - { platform: facebook,       user_url: "https://www.facebook.com/jekyll" }
#ba    - { platform: flickr,         user_url: "https://www.flickr.com/photos/jekyll" }
#ba    - { platform: github,         user_url: "https://github.com/jekyll/minima" }
#ba    - { platform: google_scholar, user_url: "https://scholar.google.com/citations?user=qc6CJjYAAAAJ" }
#ba    - { platform: instagram,      user_url: "https://www.instagram.com/jekyll" }
#ba    - { platform: keybase,        user_url: "https://keybase.io/jekyll" }
#ba    - { platform: linkedin,       user_url: "https://www.linkedin.com/in/jekyll" }
#ba    - { platform: microdotblog,   user_url: "https://micro.blog/jekyll" }
#ba    - { platform: pinterest,      user_url: "https://www.pinterest.com/jekyll" }
#ba    - { platform: stackoverflow,  user_url: "https://stackoverflow.com/users/1234567/jekyll" }
#ba    - { platform: telegram,       user_url: "https://t.me/jekyll" }
#ba    - { platform: twitter,        user_url: "https://twitter.com/jekyllrb" }
#ba    - { platform: youtube,        user_url: "https://www.youtube.com/jekyll" }

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - pubs.markdown
 - 4students.markdown
 - group.markdown
 - BodoAhrens.markdown

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag

markdown: kramdown
